INSERT INTO address (street, city, state, country, zip) VALUES ('NetajiSubhasmarg', 'Delhi', 'New Delhi', 'India', 110033);
INSERT INTO address (street, city, state, country, zip) VALUES ('lane 12', 'Janakpuri', 'New Delhi', 'India', 110022);
INSERT INTO address (street, city, state, country, zip) VALUES ('7RCR', 'CP', 'New Delhi', 'India', 110001);
INSERT INTO address (street, city, state, country, zip) VALUES ('49 Lithgow St','Abbotsford', 'Melborne','Australia', 3067);
INSERT INTO address (street, city, state, country, zip) VALUES ('232 Darebin Rd', 'Fairfield', 'Melbourne','Australia', 3078);
INSERT INTO address (street, city, state, country, zip) VALUES ('42A Cromwell St','Caulfield North', 'Melborne','Australia', 3161);
INSERT INTO address (street, city, state, country, zip) VALUES ('68 Vida St', 'Aberfeldie', 'Melbourne','Australia', 3040);
INSERT INTO address (street, city, state, country, zip) VALUES ('6/46 Richardson St', 'Essendon', 'Melbourne','Australia', 3040);
INSERT INTO address (street, city, state, country, zip) VALUES ('22 Ormond Rd','Eaglemont', 'Melborne','Australia', 3084);
INSERT INTO address (street, city, state, country, zip) VALUES ('73 Ayr St', 'Doncaster', 'Melbourne','Australia', 3108);
INSERT INTO address (street, city, state, country, zip) VALUES ('6 Fleming Cl', 'Endeavour Hills', 'Melbourne','Australia', 3802);
INSERT INTO address (street, city, state, country, zip) VALUES ('40 Castlewood St','Bentleigh East', 'Melborne','Australia', 3165);
INSERT INTO address (street, city, state, country, zip) VALUES ('2/4 Maylands Av','Balwyn North', 'Melborne','Australia', 3104);
INSERT INTO address (street, city, state, country, zip) VALUES ('2/5 Maylands Av','North', 'Sydney','Australia', 3304);
INSERT INTO address (street, city, state, country, zip) VALUES ('2/4 Fleming','Balwyn East', 'Canbera','Australia', 3103);
INSERT INTO address (street, city, state, country, zip) VALUES ('Maylands Av','Doncaster', 'Canbera','Australia', 3304);
INSERT INTO address (street, city, state, country, zip) VALUES ('2 street','Balsmic North', 'Melborne','Australia', 3124);
INSERT INTO address (street, city, state, country, zip) VALUES ('2/4 vista','aberdale', 'Melborne','Australia', 3134);
INSERT INTO address (street, city, state, country, zip) VALUES ('2/7 Maylands Av','Balwyn North', 'Melborne','Australia', 3104);
INSERT INTO address (street, city, state, country, zip) VALUES ('73', 'Doncaster', 'Melbourne','Australia', 3108);
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Abhishek',' ','Tiwari','abhishek@gmail.com','11233422',1234255,'M',1,19,03/08/2001,'student');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Bhavya',' ','dhingra','bhavya@gmail.com','1123342',1234255,'M',1,19,03/08/2001,'student');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Abhilasha',' ','Saini','abhishek@gmail.com','112334',1234255,'F',1,19,03/08/2001,'student');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Abhi',' ','Misra','abhi@gmail.com','1123343',1234234,'M',2,19,'2001-11-11','Artist');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Shivam','kumar','dubey','shivam@gmail.com','19031',12342342,'M',2,25,'1994-1-11','Software Engineer');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('shivank',' ','Sharma','shivank@gmail.com','112323',12342332,'M',3,1,'2001-11-11','Artist');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Chris','','Evans','Chrev@gmail.com','93256841',9812342,'M',1,19,'1990-2-12','Soldier');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Arther','Conan','Dolby','acondy@gmail.com','23734282',9127425,'M',1,19,'1983-12-3','Police');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Britney','','Spears','bspears02@gmail.com','212365342',5712632,'F',1,19,'2001-3-3','Singer');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Krissy','','Cela','krec987@gmail.com','89123542',8312345,'F',1,19,'2001-3-3','Police');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Chris','','Hemsworth','Thor3000@gmail.com','76728542',5956731,'M',1,19,'1990-3-3','Mechanic');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Alexander','Graham','Bell','tele6334@gmail.com','51234728',1234255,'M',1,19,'1983-12-3','Scientist');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Zachary',' ','Levi','zachey007@gmail.com','46213423',5561739,'M',1,19,'1983-12-3','Police');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Olivia',' ','Wilde','olvi@gmail.com','87623424',9126634,'F',1,19,'1990-2-12','Actress');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Christorpher','','Nolan','nolan554@gmail.com','71223428',9234255,'M',1,19,'2001-11-11','Astronaut');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Julia',' ','Michael','Juliam@gmail.com','92253423',5567391,'F',1,19,'2001-11-11','Singer');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Munna',' ','Michael','Juliam@gmail.com','92253424',5567391,'M',13,19,'2001-12-11','Actor');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Chris','','Nolan','nolan555@gmail.com','71223429',92345455,'M',16,19,'2001-11-17','Plumber');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Britn','','Spears','bspears02@gmail.com','212365322',5712632,'F',17,19,'2001-6-3','Accountant');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Krissy','','Celia','krec987@gmail.com','89122542',8312345,'F',12,19,'2001-3-4','Police');
insert into user(first_name,middle_name,last_name,email,adhar_num,phone_no,gender,address_id,age,DOB,occupation) values ('Christian','','Hemsworth','Thor3000@gmail.com','76728452',5956731,'M',1,19,'2001-5-3','Electrician');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Ford Mustang','Alex','','Jain','1997-10-23',5,1745,'Not available',100000,'DLBC44');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Chevrolet Camaro','Alpha','Kumar','Pandey','1996-10-2',3,1723,'Available',1002300,'DLBC69');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Dodge Challenger','Christ','Kumar','Sharma','1993-10-2',9,1953,'Available',1002302,'DLBC440');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Chevrolet Corvette','Olivia','','Wilde','1994-10-3',10,1852,'Not available',1002332,'DLBC430');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Nissan 370Z','Christopher','','Nolan','1992-11-4',12,1372,'Available',1002342,'DLBC420');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Dodge Challenger','Arther','Conan','Dolby','1993-10-2',9,1353,'Available',1002302,'DLBC447');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Chevrolet Corvette','Olivia','','Wilde','1994-10-3',10,1972,'Not available',1002332,'DLBC490');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Nissan 370Z','Christopher','','Nolan','1992-11-4',1,1339,'Available',1002342,'DLBC423');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Dodge Challenger','Munna',' ','Michael','1993-10-2',5,1954,'Available',1002302,'DLBC444');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Chevrolet Corvette','Olivia','','Wilde','1994-10-3',20,1352,'Not available',1002332,'DLBC330');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Nissan 370Z','Christopher','','Nolan','1992-11-4',16,1382,'Available',1002342,'DLBC220');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Dodge Challenger','Chris','','Evans','1993-10-2',12,1953,'Available',1002302,'DLBC640');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Chevrolet Corvette','Olivia','','Wilde','1994-10-3',2,1982,'Not available',1002332,'DLBC630');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Nissan 370Z','Christopher','','Nolan','1992-11-4',7,1332,'Available',1002342,'DLBC820');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Dodge Challenger','Zachary',' ','Levi','1993-10-2',4,1983,'Available',1002302,'DLBC940');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Chevrolet Corvette','Olivia','','Wilde','1994-10-3',20,2952,'Not available',1002332,'DLBC530');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Nissan 370Z','chris','','hemsworth','1992-11-4',19,1372,'Available',1002342,'DLBC480');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Dodge Challenger','Christ','Kumar','Sharma','1993-10-2',2,1353,'Available',1002302,'DLBC450');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Chevrolet Corvette','Olivia','','Wilde','1994-10-3',17,1978,'Not available',1002332,'DLBC481');
insert into cardb(model_name,first_name,middle_name,last_name,date_of_purchase,address_id,meter_reading,status,price,license_plate_num) values('Nissan 370Z','Britney','','Spears','1992-11-4',16,1832,'Available',1002342,'DLBC490');
UPDATE user SET address_id =4 WHERE adhar_num ='93256841';
UPDATE user SET address_id =5 WHERE adhar_num =  '1234255';
UPDATE user SET DOB = '2001-09-03' WHERE adhar_num ='1123342';
UPDATE user SET DOB = '2001-10-15' WHERE adhar_num ='112334';


